### ISSUE TITLE
Exception:  [!] Directory checkpoints not found

### ISSUE THREAD

**Issue by andyyuan78** [carpedm20/MemN2N-tensorflow#2]
envy@ub1404:/media/envy/data1t/os_prj/github/MemN2N-tensorflow$ PYTHONPATH=~/os_prj/github/tensorflow/_python_build python main.py --nhop 6 --mem_size 100
Read 929589 words from data/ptb.train.txt
Read 73760 words from data/ptb.valid.txt
Read 82430 words from data/ptb.test.txt
{'batch_size': 128,
 'checkpoint_dir': 'checkpoints',
 'data_dir': 'data',
 'data_name': 'ptb',
 'edim': 150,
 'init_hid': 0.1,
 'init_lr': 0.01,
 'init_std': 0.05,
 'is_test': False,
 'lindim': 75,
 'max_grad_norm': 50,
 'mem_size': 100,
 'nepoch': 100,
 'nhop': 6,
 'nwords': 10000,
 'show': False}
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    tf.app.run()
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 43, in main
    model = MemN2N(FLAGS, sess)
  File "/media/envy/data1t/os_prj/github/MemN2N-tensorflow/model.py", line 26, in __init__
    raise Exception(" [!] Directory %s not found" % self.checkpoint_dir)
Exception:  [!] Directory checkpoints not found
envy@ub1404:/media/envy/data1t/os_prj/github/MemN2N-tensorflow$

**Comment by carpedm20** [comment]
You first need to create `checkpoints` directory in the root of the project directory.
